// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgPVu0nMsLKeD7xna-7-ELIcSFhyhMOHU',
    appId: '1:490397190284:web:78177f61b64652bb6f53a9',
    messagingSenderId: '490397190284',
    projectId: 'miners-login',
    authDomain: 'miners-login.firebaseapp.com',
    storageBucket: 'miners-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1UX61oMT16XJygwd_upwbLoszV_-_RbM',
    appId: '1:490397190284:android:279842383f6eab406f53a9',
    messagingSenderId: '490397190284',
    projectId: 'miners-login',
    storageBucket: 'miners-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCil4W6j02qyBfn6vgfaR9MGM6XHgPCO3I',
    appId: '1:490397190284:ios:ddbc4868a8d4834b6f53a9',
    messagingSenderId: '490397190284',
    projectId: 'miners-login',
    storageBucket: 'miners-login.appspot.com',
    iosBundleId: 'com.example.minersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCil4W6j02qyBfn6vgfaR9MGM6XHgPCO3I',
    appId: '1:490397190284:ios:70907bdf217718946f53a9',
    messagingSenderId: '490397190284',
    projectId: 'miners-login',
    storageBucket: 'miners-login.appspot.com',
    iosBundleId: 'com.example.minersApp.RunnerTests',
  );
}
